"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Shield, Clock, ArrowRight } from "lucide-react";
import Link from "next/link";

const SECTIONS = [
  {
    id: "cookie-fundamentals",
    title: "1.0 Cookie Fundamentals",
    content: (
      <>
        <h3 className="font-heading text-xl mb-4 text-white">1.01 Definition & Purpose</h3>
        <p className="mb-6">
          This Cookie Architecture Policy ("Cookie Policy") delineates how Injaazh Global utilizes small cryptographic text files (cookies), web beacons, and persistent local storage when you access our digital infrastructure. These technologies are foundational to maintaining secure sessions, parsing user telemetry, and delivering high-performance digital experiences.
        </p>
        <h3 className="font-heading text-xl mb-4 text-white">1.02 Explicit Consent Architecture</h3>
        <p>
          In accordance with the ePrivacy Directive and GDPR standards, we strictly enforce a default-deny policy for all non-essential trackers. Telemetry and marketing payloads are only injected into your session upon explicit, verifiable consent via our advanced Cookie Consent Management Platform (CMP).
        </p>
      </>
    )
  },
  {
    id: "strictly-necessary",
    title: "2.0 Strictly Necessary Cookies",
    content: (
      <>
        <h3 className="font-heading text-xl mb-4 text-white">2.01 Core Infrastructure</h3>
        <p className="mb-6">
          These cookies are structurally vital for the web application to function. They cannot be disabled in our systems. They govern essential parameters such as load-balancing, DDoS mitigation algorithms (via Cloudflare), secure user authentication (JWT tokens), and your actual privacy consent preferences.
        </p>
        <h3 className="font-heading text-xl mb-4 text-white">2.02 Legal Precedent</h3>
        <p>
          Strictly Necessary cookies are exempt from consent requirements as they fall under the "strictly necessary for the delivery of an Information Society service" exemption. Modifying your browser to block these will result in systemic failure of the platform.
        </p>
      </>
    )
  },
  {
    id: "analytical-telemetry",
    title: "3.0 Analytical & Performance Telemetry",
    content: (
      <>
        <h3 className="font-heading text-xl mb-4 text-white">3.01 Heuristic Data Collection</h3>
        <p className="mb-6">
          We utilize enterprise-grade analytics tools to monitor aggregated user flows, identify UI/UX friction points, and measure server response latency. All payloads generated by these cookies are anonymized and mathematically obfuscated before being stored in our secure analytical warehouses.
        </p>
        <h3 className="font-heading text-xl mb-4 text-white">3.02 Associated Sub-Processors</h3>
        <p>
          Primary analytical frameworks deployed include Next.js Vercel Analytics, PostHog (self-hosted), and Google Analytics 4 (configured in strict consent mode with IP anonymization enabled).
        </p>
      </>
    )
  },
  {
    id: "marketing-syndication",
    title: "4.0 Marketing & Syndication",
    content: (
      <>
        <h3 className="font-heading text-xl mb-4 text-white">4.01 Targeted Syndication</h3>
        <p className="mb-6">
          Marketing cookies are utilized to build a digital profile of your enterprise interests, allowing us to serve highly relevant technical content and B2B retargeting advertisements across third-party networks (e.g., LinkedIn B2B Ads, Google Ads). 
        </p>
        <h3 className="font-heading text-xl mb-4 text-white">4.02 Data Broker Policies</h3>
        <p>
          We maintain a zero-tolerance policy against unauthorized data brokering. Your cookie-derived profiles are never sold to external data brokers. They are exclusively utilized for Injaazh Global's direct B2B marketing initiatives.
        </p>
      </>
    )
  },
  {
    id: "cookie-governance",
    title: "5.0 User Governance & Opt-Out",
    content: (
      <>
        <h3 className="font-heading text-xl mb-4 text-white">5.01 Managing Your Preferences</h3>
        <p className="mb-6">
          You maintain absolute sovereignty over your browser environment. You may invoke our Consent Preference Center at any time via the floating shield icon to granularly adjust your tracking permissions. Revoking consent will immediately trigger a client-side script to purge all non-essential cookies from your local cache.
        </p>
        <h3 className="font-heading text-xl mb-4 text-white">5.02 Browser-Level Overrides</h3>
        <p>
          Furthermore, our architecture respects global "Do Not Track" (DNT) headers and the newer Global Privacy Control (GPC) signals transmitted natively by privacy-focused browsers like Brave and Firefox.
        </p>
      </>
    )
  }
];

export default function CookiePolicy() {
  const [activeSection, setActiveSection] = useState(SECTIONS[0].id);

  // Intersection Observer for scroll spy
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      { rootMargin: "-20% 0px -80% 0px" } // Trigger when section is near top
    );

    SECTIONS.forEach((section) => {
      const element = document.getElementById(section.id);
      if (element) observer.observe(element);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <main className="w-full min-h-screen bg-[#060608] text-white relative overflow-hidden selection:bg-[#FACC15] selection:text-[#060608]">
      {/* Background Decorative Elements */}
      <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-[#6324FC]/5 blur-[150px] rounded-full pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-[#FACC15]/5 blur-[150px] rounded-full pointer-events-none" />
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.03] pointer-events-none mix-blend-overlay fixed" />
      
      <div className="max-w-[1400px] mx-auto px-6 md:px-12 relative z-10">
        
        {/* Cinematic Header */}
        <section className="pt-32 pb-16 md:pt-40 md:pb-24 border-b border-white/5">
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          className="max-w-4xl"
        >
          <div className="font-heading  text-[#FACC15] tracking-[0.5em] text-[10px] capitalize mb-8 flex items-center gap-4">
            <span className="w-12 h-[1px] bg-[#FACC15]" /> 
            Telemetry Architecture
          </div>
          
          <h1 className="font-heading text-5xl md:text-7xl leading-[0.85] tracking-tighter capitalize mb-12">
            COOKIE <br/>
            <span className="stroke-text text-transparent italic opacity-50">POLICY</span>
          </h1>
          
          <div className="flex flex-col md:flex-row items-start md:items-center gap-8 text-white/40 font-heading  text-xs capitalize tracking-widest border-t border-white/10 pt-8">
            <div className="flex items-center gap-3">
              <Clock className="w-4 h-4 text-[#FACC15]" />
              <span>Effective Date: Q2 2026</span>
            </div>
            <span className="hidden md:block w-1 h-1 bg-white/20 rounded-full" />
            <div className="flex items-center gap-3">
              <Shield className="w-4 h-4 text-[#6324FC]" />
              <span>Document ID: INJ-CK-301</span>
            </div>
          </div>
        </motion.div>
        </section>
        {/* Two Column Layout */}
        <div className="flex flex-col lg:flex-row gap-16 lg:gap-32">
          
          {/* Left: Sticky Table of Contents */}
          <div className="lg:w-1/3 hidden lg:block">
            <div className="sticky top-40 space-y-8">
              <h4 className="font-heading  text-[10px] text-white/30 tracking-widest capitalize mb-8">Cookie Framework</h4>
              <nav className="flex flex-col gap-6 relative before:absolute before:left-0 before:top-2 before:bottom-2 before:w-[1px] before:bg-white/10">
                {SECTIONS.map((section) => (
                  <a 
                    key={section.id} 
                    href={`#${section.id}`}
                    className={`relative pl-8 font-heading  tracking-tight transition-all duration-300 ${activeSection === section.id ? 'text-[#FACC15]' : 'text-white/40 hover:text-white/80'}`}
                  >
                    {/* Active Indicator Line */}
                    <span className={`absolute left-0 top-1/2 -translate-y-1/2 w-[2px] bg-[#FACC15] transition-all duration-300 ${activeSection === section.id ? 'h-full opacity-100 shadow-[0_0_10px_rgba(250,204,21,0.8)]' : 'h-0 opacity-0'}`} />
                    {section.title}
                  </a>
                ))}
              </nav>
            </div>
          </div>

          {/* Right: Legal Content (The "Document") */}
          <div className="lg:w-2/3">
            <div className="prose prose-invert prose-lg max-w-none">
              
              <div className="mb-20 p-8 border border-[#FACC15]/20 bg-[#FACC15]/5 rounded-2xl backdrop-blur-sm">
                <p className="font-sans font-light text-white/80 text-xl leading-relaxed m-0">
                  Transparency in telemetry is paramount. This document maps the precise tracking mechanisms we deploy, categorizing them by technical necessity and ensuring you retain full sovereignty over your digital footprint while interfacing with our agency.
                </p>
              </div>

              <div className="space-y-32">
                {SECTIONS.map((section, idx) => (
                  <motion.div 
                    key={section.id} 
                    id={section.id}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                    className="scroll-mt-40 relative py-16 md:py-24 border-b border-white/5"
                  >
                    {/* Section Number Watermark */}
                    <div className="absolute -left-12 -top-12 font-heading text-[8rem] leading-none text-white/[0.02] pointer-events-none select-none hidden md:block">
                      0{idx + 1}
                    </div>
                    
                    <h2 className="font-heading text-5xl md:text-7xl leading-[0.85] tracking-tighter capitalize mb-12 text-[#6324FC] border-b border-white/10 pb-8 relative z-10">
                      {section.title}
                    </h2>
                    
                    <div className="font-sans font-light text-white/60  leading-loose space-y-8 relative z-10">
                      {section.content}
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Consent & Contact Footer */}
              <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                className="mt-40 p-12 border border-[#FACC15]/30 bg-gradient-to-br from-[#FACC15]/10 to-transparent rounded-[3rem] relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 w-64 h-64 bg-[#6324FC]/20 blur-[100px]" />
                
                <h3 className="font-heading text-4xl tracking-tight capitalize mb-6 text-white relative z-10">Manage Your Preferences</h3>
                <p className="font-sans text-white/70  leading-relaxed mb-10 relative z-10 max-w-2xl">
                  You can purge your existing telemetry settings or review our master Privacy framework at any time. For technical inquiries regarding our cookie architecture, contact our compliance engineering team.
                </p>
                
                <div className="flex flex-col sm:flex-row gap-6 relative z-10">
                  <Link href="/privacy-policy" className="inline-flex items-center justify-center gap-3 px-8 py-5 bg-white text-black font-heading text-sm tracking-widest capitalize rounded-full hover:bg-[#FACC15] transition-colors">
                    Privacy Policy <ArrowRight className="w-4 h-4" />
                  </Link>
                  <a href="mailto:privacy@injaazh.com" className="inline-flex items-center justify-center gap-3 px-8 py-5 border border-white/20 text-white font-heading text-sm tracking-widest capitalize rounded-full hover:bg-white/5 transition-colors">
                    Email Compliance
                  </a>
                </div>
              </motion.div>

            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
